version: '3'
services:
  notebook:
    tty: true
    build: ./Build
    user: root
    ports:
      - 8888:8888
    environment:
      TZ: Asia/Tokyo
      GRANT_SUDO: "yes"
    volumes:
      - ./volumes/notebooks:/home/jovyan/notebooks
    command: "/usr/bin/supervisord"