Vagrant.configure("2") do |config|
    Encoding.default_external = 'UTF-8'
    config.vm.box = "Sakoda/PSNotebook2019"
    config.vm.guest = :windows
    config.vm.communicator = "winrm"
    config.vm.network :forwarded_port, guest: 3389, host: 13389
    config.vm.network :forwarded_port, guest: 5985, host: 15985, id: "winrm", auto_correct: true
    config.vm.synced_folder ".", "/Vagrant", type: "smb", smb_password: "P@ssw0rd", smb_username: "Notebook"
    config.vm.provision "shell", inline: <<-SHELL
        slmgr /rearm
    SHELL
    config.vm.provision "shell", run: "always", inline: <<-SHELL
        chcp 65001
        $jup = (cmd /c where jupyter-notebook)
        Invoke-Item $jup
    SHELL
end
